# Generated by Django 5.1.5 on 2025-02-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auction_listing',
            new_name='item',
        ),
    ]
