FROM python:3.12-slim

# Environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install uv 
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Add uv to PATH
RUN mv /root/.local/bin/uv /usr/local/bin/


# Copy and install dependencies
COPY requirements.txt .
RUN uv venv && uv pip install -r requirements.txt

ENV PATH="/app/.venv/bin:$PATH"

# Copy rest of the app
COPY . .

# Run Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
