# Generated by Django 5.1.6 on 2025-03-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_user_id_following_post_like_image_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="caption",
            new_name="content",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
